project_id = "bfwohzcugtwbhhxdqgme"

[functions.stripe-webhook]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.stripe-create-checkout-session]
verify_jwt = false

[functions.stripe-create-invoice-payment-link]
verify_jwt = false

[functions.stripe-void-invoice]
verify_jwt = false

[functions.twilio-sms-webhook]
verify_jwt = false