/**
 * Client-side sample data for payment reconciliation.
 * Used as fallback when the database migration hasn't been applied yet
 * or the query returns empty results.
 */
import type { OrderPayment, OrderExtra, OutstandingOrder, ReconciliationStats } from '../types/reconciliation.types';

// ---------------------------------------------------------------------------
// Sample order_payments — matched
// ---------------------------------------------------------------------------
export const SAMPLE_MATCHED_PAYMENTS: OrderPayment[] = [
  {
    id: 'sample-mp-001',
    user_id: null,
    order_id: 'sample-ord-001',
    source: 'stripe',
    external_id: 'pi_sample_thompson_deposit',
    amount: 1325.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3QxY7kABC_Thompson',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    orders: { id: 'sample-ord-001', order_number: 1, customer_name: 'Margaret Thompson', person_id: null },
  },
  {
    id: 'sample-mp-002',
    user_id: null,
    order_id: 'sample-ord-002',
    source: 'stripe',
    external_id: 'pi_sample_patel_deposit',
    amount: 1600.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3RaB2kDEF_Patel',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 58 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 58 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 58 * 86400000).toISOString(),
    orders: { id: 'sample-ord-002', order_number: 2, customer_name: 'James & Sarah Patel', person_id: null },
  },
  {
    id: 'sample-mp-003',
    user_id: null,
    order_id: 'sample-ord-003',
    source: 'stripe',
    external_id: 'pi_sample_williams_deposit',
    amount: 900.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3PwX9kGHI_Williams',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    orders: { id: 'sample-ord-003', order_number: 3, customer_name: 'Robert Williams', person_id: null },
  },
  {
    id: 'sample-mp-004',
    user_id: null,
    order_id: 'sample-ord-003',
    source: 'revolut',
    external_id: 'rev_sample_williams_final',
    amount: 1200.00,
    currency: 'GBP',
    payment_type: 'final',
    reference: 'WILLIAMS MEMORIAL FINAL',
    match_reason: 'Amount + name match',
    match_candidates: null,
    matched_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    orders: { id: 'sample-ord-003', order_number: 3, customer_name: 'Robert Williams', person_id: null },
  },
  {
    id: 'sample-mp-005',
    user_id: null,
    order_id: 'sample-ord-005',
    source: 'revolut',
    external_id: 'rev_sample_morrison_deposit',
    amount: 1400.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'MORRISON headstone dep',
    match_reason: 'Reference contains customer surname',
    match_candidates: null,
    matched_at: new Date(Date.now() - 62 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 62 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 62 * 86400000).toISOString(),
    orders: { id: 'sample-ord-005', order_number: 5, customer_name: 'David & Ann Morrison', person_id: null },
  },
  {
    id: 'sample-mp-006',
    user_id: null,
    order_id: 'sample-ord-006',
    source: 'stripe',
    external_id: 'pi_sample_green_deposit',
    amount: 425.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3ScD4kJKL_Green',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    orders: { id: 'sample-ord-006', order_number: 6, customer_name: 'Patricia Green', person_id: null },
  },
];

// ---------------------------------------------------------------------------
// Sample order_payments — unmatched
// ---------------------------------------------------------------------------
export const SAMPLE_UNMATCHED_PAYMENTS: OrderPayment[] = [
  {
    id: 'sample-up-001',
    user_id: null,
    order_id: null,
    source: 'revolut',
    external_id: 'rev_sample_unmatched_1',
    amount: 2200.00,
    currency: 'GBP',
    payment_type: null,
    reference: 'MEMORIAL PAYMENT KUMAR',
    match_reason: 'No matching orders found for surname "KUMAR"',
    match_candidates: [
      {
        order_id: 'sample-ord-002',
        order_ref: '2',
        customer_name: 'James & Sarah Patel',
        expected_amount: 1600.00,
        confidence: 'amount' as const,
        reason: 'Closest amount match',
      },
    ],
    matched_at: null,
    matched_by: null,
    status: 'unmatched',
    received_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    orders: null,
  },
  {
    id: 'sample-up-002',
    user_id: null,
    order_id: null,
    source: 'stripe',
    external_id: 'pi_sample_unmatched_2',
    amount: 750.00,
    currency: 'GBP',
    payment_type: null,
    reference: 'pi_3TfG7kMNO_unknown',
    match_reason: 'Stripe customer ID not found in system',
    match_candidates: null,
    matched_at: null,
    matched_by: null,
    status: 'unmatched',
    received_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    orders: null,
  },
  {
    id: 'sample-up-003',
    user_id: null,
    order_id: null,
    source: 'revolut',
    external_id: 'rev_sample_unmatched_3',
    amount: 1325.00,
    currency: 'GBP',
    payment_type: null,
    reference: 'HEADSTONE DEPOSIT',
    match_reason: 'Amount matches multiple orders — manual review needed',
    match_candidates: [
      {
        order_id: 'sample-ord-001',
        order_ref: '1',
        customer_name: 'Margaret Thompson',
        expected_amount: 1325.00,
        confidence: 'exact' as const,
        reason: 'Amount matches expected deposit',
      },
    ],
    matched_at: null,
    matched_by: null,
    status: 'unmatched',
    received_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    orders: null,
  },
];

// ---------------------------------------------------------------------------
// Sample outstanding orders
// ---------------------------------------------------------------------------
export const SAMPLE_OUTSTANDING_ORDERS: OutstandingOrder[] = [
  {
    id: 'sample-ord-001',
    order_number: 1,
    customer_name: 'Margaret Thompson',
    customer_email: 'margaret.thompson@email.com',
    customer_phone: '07712345678',
    person_id: null,
    sku: 'HS-2048-GRY',
    material: 'Granite',
    color: 'Dark Grey',
    location: "St Mary's Churchyard, Beaconsfield",
    value: 2450.00,
    total_order_value: 2650.00,
    amount_paid: 1325.00,
    balance_due: 1325.00,
    final_invoice_sent_at: null,
    final_invoice_id: null,
    deposit_date: new Date(Date.now() - 75 * 86400000).toISOString().slice(0, 10),
    due_date: '2026-04-30',
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
  },
  {
    id: 'sample-ord-002',
    order_number: 2,
    customer_name: 'James & Sarah Patel',
    customer_email: 'james.patel@email.com',
    customer_phone: '07798765432',
    person_id: null,
    sku: 'HS-3072-BLK',
    material: 'Marble',
    color: 'Black',
    location: 'Amersham Cemetery',
    value: 3200.00,
    total_order_value: 3200.00,
    amount_paid: 1600.00,
    balance_due: 1600.00,
    final_invoice_sent_at: null,
    final_invoice_id: null,
    deposit_date: new Date(Date.now() - 58 * 86400000).toISOString().slice(0, 10),
    due_date: '2026-05-15',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'sample-ord-005',
    order_number: 5,
    customer_name: 'David & Ann Morrison',
    customer_email: 'morrison.family@email.com',
    customer_phone: '07432109876',
    person_id: null,
    sku: 'HS-4096-RST',
    material: 'Sandstone',
    color: 'Rustic',
    location: 'Chesham Bois Burial Ground',
    value: 2800.00,
    total_order_value: 3050.00,
    amount_paid: 1400.00,
    balance_due: 1650.00,
    final_invoice_sent_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    final_invoice_id: null,
    deposit_date: new Date(Date.now() - 62 * 86400000).toISOString().slice(0, 10),
    due_date: '2026-05-20',
    created_at: new Date(Date.now() - 65 * 86400000).toISOString(),
  },
  {
    id: 'sample-ord-006',
    order_number: 6,
    customer_name: 'Patricia Green',
    customer_email: 'p.green@email.com',
    customer_phone: '07321098765',
    person_id: null,
    sku: 'REN-001',
    material: 'Granite',
    color: 'Dark Grey',
    location: 'Marlow Cemetery',
    value: 850.00,
    total_order_value: 850.00,
    amount_paid: 425.00,
    balance_due: 425.00,
    final_invoice_sent_at: null,
    final_invoice_id: null,
    deposit_date: new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10),
    due_date: '2026-04-15',
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
];

// ---------------------------------------------------------------------------
// Sample order extras
// ---------------------------------------------------------------------------
export const SAMPLE_ORDER_EXTRAS: OrderExtra[] = [
  {
    id: 'sample-ex-001',
    user_id: null,
    order_id: 'sample-ord-001',
    source: 'gmail',
    source_ref: null,
    change_type: 'photo_plaque',
    description: 'Photo plaque addition — ceramic oval with gilded edge',
    quote_snippet: "Yes please go ahead with the photo plaque. The oval one with the gold edge looks lovely. We'll send the photo over this weekend.",
    quote_date: new Date(Date.now() - 18 * 86400000).toISOString(),
    quote_sender: 'Margaret Thompson',
    confidence: 'high',
    confidence_reason: 'Customer explicitly agreed to photo plaque addition. Price discussed in previous message (£185).',
    suggested_amount: 185.00,
    status: 'pending',
    invoice_line_item_id: null,
    detected_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    actioned_by: null,
    actioned_at: null,
    orders: { id: 'sample-ord-001', order_number: 1, customer_name: 'Margaret Thompson', person_id: null },
  },
  {
    id: 'sample-ex-002',
    user_id: null,
    order_id: 'sample-ord-002',
    source: 'whatsapp',
    source_ref: null,
    change_type: 'inscription_increase',
    description: 'Inscription extended by 24 additional characters',
    quote_snippet: "We'd like to add \"Forever in our hearts, always in our thoughts\" below the main text. Is that OK? Happy to pay the extra.",
    quote_date: new Date(Date.now() - 12 * 86400000).toISOString(),
    quote_sender: 'Sarah Patel',
    confidence: 'high',
    confidence_reason: 'Customer confirmed additional text and acknowledged extra cost. 24 chars at £3.50/char = £84.',
    suggested_amount: 84.00,
    status: 'pending',
    invoice_line_item_id: null,
    detected_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    actioned_by: null,
    actioned_at: null,
    orders: { id: 'sample-ord-002', order_number: 2, customer_name: 'James & Sarah Patel', person_id: null },
  },
  {
    id: 'sample-ex-003',
    user_id: null,
    order_id: 'sample-ord-005',
    source: 'gmail',
    source_ref: null,
    change_type: 'colour_change',
    description: 'Stone colour change from Dark Grey to Rustic Sandstone',
    quote_snippet: "We've been thinking and actually prefer the rustic look. Would it be possible to change to the sandstone? What would the difference in cost be?",
    quote_date: new Date(Date.now() - 25 * 86400000).toISOString(),
    quote_sender: 'David Morrison',
    confidence: 'medium',
    confidence_reason: 'No price confirmed in conversation — verify material cost difference with Matthew before invoicing.',
    suggested_amount: 250.00,
    status: 'pending',
    invoice_line_item_id: null,
    detected_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    actioned_by: null,
    actioned_at: null,
    orders: { id: 'sample-ord-005', order_number: 5, customer_name: 'David & Ann Morrison', person_id: null },
  },
  {
    id: 'sample-ex-004',
    user_id: null,
    order_id: 'sample-ord-001',
    source: 'phone_note',
    source_ref: null,
    change_type: 'vase',
    description: 'Granite vase to match headstone discussed on call',
    quote_snippet: "Margaret called to ask about adding a matching granite vase. Quoted £120. She said she'd think about it and call back.",
    quote_date: new Date(Date.now() - 8 * 86400000).toISOString(),
    quote_sender: 'Aylin',
    confidence: 'medium',
    confidence_reason: 'Customer was quoted but has not confirmed yet. Awaiting callback.',
    suggested_amount: 120.00,
    status: 'pending',
    invoice_line_item_id: null,
    detected_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    actioned_by: null,
    actioned_at: null,
    orders: { id: 'sample-ord-001', order_number: 1, customer_name: 'Margaret Thompson', person_id: null },
  },
  {
    id: 'sample-ex-005',
    user_id: null,
    order_id: 'sample-ord-002',
    source: 'gmail',
    source_ref: null,
    change_type: 'other',
    description: 'Possible kerb set addition mentioned in passing',
    quote_snippet: 'By the way, do you also do kerb sets? Just wondering for future reference.',
    quote_date: new Date(Date.now() - 20 * 86400000).toISOString(),
    quote_sender: 'James Patel',
    confidence: 'low',
    confidence_reason: 'Customer only enquired about kerb sets — no confirmation or pricing discussed. Likely not actionable.',
    suggested_amount: null,
    status: 'pending',
    invoice_line_item_id: null,
    detected_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    actioned_by: null,
    actioned_at: null,
    orders: { id: 'sample-ord-002', order_number: 2, customer_name: 'James & Sarah Patel', person_id: null },
  },
];

// ---------------------------------------------------------------------------
// Sample stats
// ---------------------------------------------------------------------------
export const SAMPLE_STATS: ReconciliationStats = {
  received_this_month: 4275.00,
  matched_count: 6,
  unmatched_count: 3,
  outstanding_total: 5000.00,
};
