/**
 * Client-side sample data for payment reconciliation.
 * Used as fallback when the database migration hasn't been applied yet
 * or the query returns empty results.
 */
import type { OrderPayment, ReconciliationStats } from '../types/reconciliation.types';

// ---------------------------------------------------------------------------
// Sample order_payments — matched
// ---------------------------------------------------------------------------
export const SAMPLE_MATCHED_PAYMENTS: OrderPayment[] = [
  {
    id: 'sample-mp-001',
    user_id: null,
    order_id: 'sample-ord-001',
    source: 'stripe',
    external_id: 'pi_sample_thompson_deposit',
    amount: 1325.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3QxY7kABC_Thompson',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    orders: { id: 'sample-ord-001', order_number: 1, customer_name: 'Margaret Thompson', person_id: null },
  },
  {
    id: 'sample-mp-002',
    user_id: null,
    order_id: 'sample-ord-002',
    source: 'stripe',
    external_id: 'pi_sample_patel_deposit',
    amount: 1600.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3RaB2kDEF_Patel',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 58 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 58 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 58 * 86400000).toISOString(),
    orders: { id: 'sample-ord-002', order_number: 2, customer_name: 'James & Sarah Patel', person_id: null },
  },
  {
    id: 'sample-mp-003',
    user_id: null,
    order_id: 'sample-ord-003',
    source: 'stripe',
    external_id: 'pi_sample_williams_deposit',
    amount: 900.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3PwX9kGHI_Williams',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 130 * 86400000).toISOString(),
    orders: { id: 'sample-ord-003', order_number: 3, customer_name: 'Robert Williams', person_id: null },
  },
  {
    id: 'sample-mp-004',
    user_id: null,
    order_id: 'sample-ord-003',
    source: 'revolut',
    external_id: 'rev_sample_williams_final',
    amount: 1200.00,
    currency: 'GBP',
    payment_type: 'final',
    reference: 'WILLIAMS MEMORIAL FINAL',
    match_reason: 'Amount + name match',
    match_candidates: null,
    matched_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    orders: { id: 'sample-ord-003', order_number: 3, customer_name: 'Robert Williams', person_id: null },
  },
  {
    id: 'sample-mp-005',
    user_id: null,
    order_id: 'sample-ord-005',
    source: 'revolut',
    external_id: 'rev_sample_morrison_deposit',
    amount: 1400.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'MORRISON headstone dep',
    match_reason: 'Reference contains customer surname',
    match_candidates: null,
    matched_at: new Date(Date.now() - 62 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 62 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 62 * 86400000).toISOString(),
    orders: { id: 'sample-ord-005', order_number: 5, customer_name: 'David & Ann Morrison', person_id: null },
  },
  {
    id: 'sample-mp-006',
    user_id: null,
    order_id: 'sample-ord-006',
    source: 'stripe',
    external_id: 'pi_sample_green_deposit',
    amount: 425.00,
    currency: 'GBP',
    payment_type: 'deposit',
    reference: 'pi_3ScD4kJKL_Green',
    match_reason: 'metadata.order_id present',
    match_candidates: null,
    matched_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    matched_by: 'auto',
    status: 'matched',
    received_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    orders: { id: 'sample-ord-006', order_number: 6, customer_name: 'Patricia Green', person_id: null },
  },
];

// ---------------------------------------------------------------------------
// Sample order_payments — unmatched
// ---------------------------------------------------------------------------
export const SAMPLE_UNMATCHED_PAYMENTS: OrderPayment[] = [
  {
    id: 'sample-up-001',
    user_id: null,
    order_id: null,
    source: 'revolut',
    external_id: 'rev_sample_unmatched_1',
    amount: 2200.00,
    currency: 'GBP',
    payment_type: null,
    reference: 'MEMORIAL PAYMENT KUMAR',
    match_reason: 'No matching orders found for surname "KUMAR"',
    match_candidates: [
      {
        order_id: 'sample-ord-002',
        order_ref: '2',
        customer_name: 'James & Sarah Patel',
        expected_amount: 1600.00,
        confidence: 'amount' as const,
        reason: 'Closest amount match',
      },
    ],
    matched_at: null,
    matched_by: null,
    status: 'unmatched',
    received_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    orders: null,
  },
  {
    id: 'sample-up-002',
    user_id: null,
    order_id: null,
    source: 'stripe',
    external_id: 'pi_sample_unmatched_2',
    amount: 750.00,
    currency: 'GBP',
    payment_type: null,
    reference: 'pi_3TfG7kMNO_unknown',
    match_reason: 'Stripe customer ID not found in system',
    match_candidates: null,
    matched_at: null,
    matched_by: null,
    status: 'unmatched',
    received_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    orders: null,
  },
  {
    id: 'sample-up-003',
    user_id: null,
    order_id: null,
    source: 'revolut',
    external_id: 'rev_sample_unmatched_3',
    amount: 1325.00,
    currency: 'GBP',
    payment_type: null,
    reference: 'HEADSTONE DEPOSIT',
    match_reason: 'Amount matches multiple orders — manual review needed',
    match_candidates: [
      {
        order_id: 'sample-ord-001',
        order_ref: '1',
        customer_name: 'Margaret Thompson',
        expected_amount: 1325.00,
        confidence: 'exact' as const,
        reason: 'Amount matches expected deposit',
      },
    ],
    matched_at: null,
    matched_by: null,
    status: 'unmatched',
    received_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    raw_data: null,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    orders: null,
  },
];

// ---------------------------------------------------------------------------
// Sample stats
// ---------------------------------------------------------------------------
export const SAMPLE_STATS: ReconciliationStats = {
  received_this_month: 4275.00,
  matched_count: 6,
  unmatched_count: 3,
  outstanding_total: 5000.00,
};
