import type { PermitOrder } from '../types/permitTracker.types';

/**
 * Sample permit orders for demonstration when the database migration
 * hasn't been applied yet or the query fails.
 */
export const SAMPLE_PERMIT_ORDERS: PermitOrder[] = [
  // === ACTION NEEDED (29+ days) ===
  {
    id: 'sample-001',
    order_number: 1042,
    customer_name: 'Margaret Thompson',
    customer_email: 'margaret.t@email.com',
    person_name: 'William Thompson',
    deceased_name: 'William Thompson',
    order_type: 'Headstone',
    location: 'Landican Cemetery',
    memorial_type: 'Granite Headstone',
    permit_status: 'pending',
    permit_form_sent_at: null,
    permit_submitted_at: '2026-02-15T10:00:00Z',
    permit_approved_at: null,
    permit_correspondence_email: 'aylin@churchillmemorials.com',
    permit_cemetery_email: 'permits@landican-cemetery.gov.uk',
    permit_gmail_thread_id: 'thread-abc123',
    cemetery_id: 'cem-001',
    cemetery: {
      id: 'cem-001',
      name: 'Landican Cemetery',
      primary_email: 'permits@landican-cemetery.gov.uk',
      phone: '0151 677 2361',
      address: 'Arrowe Park Road, Birkenhead, CH49 5LW',
      avg_approval_days: 21,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-01T14:00:00Z',
  },
  {
    id: 'sample-002',
    order_number: 1038,
    customer_name: 'David Williams',
    customer_email: 'david.w@email.com',
    person_name: 'Eleanor Williams',
    deceased_name: 'Eleanor Williams',
    order_type: 'Memorial',
    location: 'Allerton Cemetery',
    memorial_type: 'Marble Tablet',
    permit_status: 'pending',
    permit_form_sent_at: null,
    permit_submitted_at: '2026-02-20T11:30:00Z',
    permit_approved_at: null,
    permit_correspondence_email: 'aylin@churchillmemorials.com',
    permit_cemetery_email: 'admin@allertoncemetery.co.uk',
    permit_gmail_thread_id: 'thread-def456',
    cemetery_id: 'cem-002',
    cemetery: {
      id: 'cem-002',
      name: 'Allerton Cemetery',
      primary_email: 'admin@allertoncemetery.co.uk',
      phone: '0151 233 3052',
      address: 'Allerton Road, Liverpool, L18 1JG',
      avg_approval_days: 28,
      notes: 'Slow to respond — chase after 14 days',
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-02-20T11:30:00Z',
  },

  // === CHASE THIS WEEK (15-28 days) ===
  {
    id: 'sample-003',
    order_number: 1051,
    customer_name: 'Sarah Mitchell',
    customer_email: 'sarah.m@email.com',
    person_name: 'James Mitchell',
    deceased_name: 'James Mitchell',
    order_type: 'Headstone',
    location: 'Anfield Cemetery',
    memorial_type: 'Black Granite Headstone',
    permit_status: 'pending',
    permit_form_sent_at: null,
    permit_submitted_at: '2026-03-10T09:00:00Z',
    permit_approved_at: null,
    permit_correspondence_email: null,
    permit_cemetery_email: null,
    permit_gmail_thread_id: null,
    cemetery_id: 'cem-003',
    cemetery: {
      id: 'cem-003',
      name: 'Anfield Cemetery',
      primary_email: 'cemetery.anfield@liverpool.gov.uk',
      phone: '0151 233 3015',
      address: 'Priory Road, Liverpool, L4 2SL',
      avg_approval_days: 18,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-02-25T11:00:00Z',
    updated_at: '2026-03-10T09:00:00Z',
  },
  {
    id: 'sample-004',
    order_number: 1053,
    customer_name: 'Robert Clarke',
    customer_email: 'r.clarke@email.com',
    person_name: 'Dorothy Clarke',
    deceased_name: 'Dorothy Clarke',
    order_type: 'Memorial',
    location: 'Landican Cemetery',
    memorial_type: 'Grey Granite Memorial',
    permit_status: 'pending',
    permit_form_sent_at: null,
    permit_submitted_at: '2026-03-12T14:00:00Z',
    permit_approved_at: null,
    permit_correspondence_email: 'aylin@churchillmemorials.com',
    permit_cemetery_email: 'permits@landican-cemetery.gov.uk',
    permit_gmail_thread_id: null,
    cemetery_id: 'cem-001',
    cemetery: {
      id: 'cem-001',
      name: 'Landican Cemetery',
      primary_email: 'permits@landican-cemetery.gov.uk',
      phone: '0151 677 2361',
      address: 'Arrowe Park Road, Birkenhead, CH49 5LW',
      avg_approval_days: 21,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-12T14:00:00Z',
  },

  // === AWAITING CUSTOMER SIGNATURE (form_sent) ===
  {
    id: 'sample-005',
    order_number: 1060,
    customer_name: 'Patricia Green',
    customer_email: 'patricia.green@email.com',
    person_name: 'Harold Green',
    deceased_name: 'Harold Green',
    order_type: 'Headstone',
    location: 'Smithdown Cemetery',
    memorial_type: 'Sandstone Headstone',
    permit_status: 'form_sent',
    permit_form_sent_at: '2026-03-18T09:30:00Z',
    permit_submitted_at: null,
    permit_approved_at: null,
    permit_correspondence_email: null,
    permit_cemetery_email: null,
    permit_gmail_thread_id: null,
    cemetery_id: 'cem-004',
    cemetery: {
      id: 'cem-004',
      name: 'Smithdown Cemetery',
      primary_email: 'smithdown@liverpool.gov.uk',
      phone: '0151 233 3099',
      address: 'Smithdown Road, Liverpool, L15 5AG',
      avg_approval_days: 14,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-18T09:30:00Z',
  },
  {
    id: 'sample-006',
    order_number: 1062,
    customer_name: 'John Taylor',
    customer_email: 'john.taylor99@email.com',
    person_name: 'Mary Taylor',
    deceased_name: 'Mary Taylor',
    order_type: 'Memorial',
    location: 'Allerton Cemetery',
    memorial_type: 'White Marble Tablet',
    permit_status: 'form_sent',
    permit_form_sent_at: '2026-03-22T11:00:00Z',
    permit_submitted_at: null,
    permit_approved_at: null,
    permit_correspondence_email: null,
    permit_cemetery_email: null,
    permit_gmail_thread_id: null,
    cemetery_id: 'cem-002',
    cemetery: {
      id: 'cem-002',
      name: 'Allerton Cemetery',
      primary_email: 'admin@allertoncemetery.co.uk',
      phone: '0151 233 3052',
      address: 'Allerton Road, Liverpool, L18 1JG',
      avg_approval_days: 28,
      notes: 'Slow to respond — chase after 14 days',
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-03-15T14:00:00Z',
    updated_at: '2026-03-22T11:00:00Z',
  },

  // === ON TRACK (0-14 days) ===
  {
    id: 'sample-007',
    order_number: 1068,
    customer_name: 'Angela Roberts',
    customer_email: 'a.roberts@email.com',
    person_name: 'Thomas Roberts',
    deceased_name: 'Thomas Roberts',
    order_type: 'Headstone',
    location: 'Anfield Cemetery',
    memorial_type: 'Dark Grey Granite',
    permit_status: 'pending',
    permit_form_sent_at: null,
    permit_submitted_at: '2026-03-25T10:00:00Z',
    permit_approved_at: null,
    permit_correspondence_email: 'aylin@churchillmemorials.com',
    permit_cemetery_email: 'cemetery.anfield@liverpool.gov.uk',
    permit_gmail_thread_id: 'thread-ghi789',
    cemetery_id: 'cem-003',
    cemetery: {
      id: 'cem-003',
      name: 'Anfield Cemetery',
      primary_email: 'cemetery.anfield@liverpool.gov.uk',
      phone: '0151 233 3015',
      address: 'Priory Road, Liverpool, L4 2SL',
      avg_approval_days: 18,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-25T10:00:00Z',
  },
  {
    id: 'sample-008',
    order_number: 1070,
    customer_name: 'Michael Evans',
    customer_email: 'm.evans@email.com',
    person_name: 'Betty Evans',
    deceased_name: 'Betty Evans',
    order_type: 'Memorial',
    location: 'Smithdown Cemetery',
    memorial_type: 'Portland Stone Memorial',
    permit_status: 'pending',
    permit_form_sent_at: null,
    permit_submitted_at: '2026-03-28T15:00:00Z',
    permit_approved_at: null,
    permit_correspondence_email: null,
    permit_cemetery_email: null,
    permit_gmail_thread_id: null,
    cemetery_id: 'cem-004',
    cemetery: {
      id: 'cem-004',
      name: 'Smithdown Cemetery',
      primary_email: 'smithdown@liverpool.gov.uk',
      phone: '0151 233 3099',
      address: 'Smithdown Road, Liverpool, L15 5AG',
      avg_approval_days: 14,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-03-22T10:00:00Z',
    updated_at: '2026-03-28T15:00:00Z',
  },
  {
    id: 'sample-009',
    order_number: 1071,
    customer_name: 'Christine Baker',
    customer_email: 'c.baker@email.com',
    person_name: 'George Baker',
    deceased_name: 'George Baker',
    order_type: 'Headstone',
    location: 'Landican Cemetery',
    memorial_type: 'Emerald Pearl Granite',
    permit_status: 'customer_completed',
    permit_form_sent_at: '2026-03-15T09:00:00Z',
    permit_submitted_at: '2026-03-30T10:00:00Z',
    permit_approved_at: null,
    permit_correspondence_email: null,
    permit_cemetery_email: null,
    permit_gmail_thread_id: null,
    cemetery_id: 'cem-001',
    cemetery: {
      id: 'cem-001',
      name: 'Landican Cemetery',
      primary_email: 'permits@landican-cemetery.gov.uk',
      phone: '0151 677 2361',
      address: 'Arrowe Park Road, Birkenhead, CH49 5LW',
      avg_approval_days: 21,
      notes: null,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    created_at: '2026-03-10T11:00:00Z',
    updated_at: '2026-03-30T10:00:00Z',
  },
];
